import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { PrismaService } from '../../common/database/prisma.service';
import { EventBusService, DomainEvent } from '../../common/events/event-bus.service';

@Injectable()
export class ItilAutomationService implements OnModuleInit {
  private readonly logger = new Logger(ItilAutomationService.name);

  constructor(
    private prisma: PrismaService,
    private eventBus: EventBusService,
  ) {}

  onModuleInit() {
    this.eventBus.on('ticket.created', (event: DomainEvent) => {
      this.handleTicketCreated(event).catch(err =>
        this.logger.error(`ITIL Automation error: ${err.message}`),
      );
    });
    this.logger.log('ITIL Automation Service listening for ticket events');
  }

  async handleTicketCreated(event: DomainEvent) {
    const ticket = event.payload;
    if (!ticket) return;

    // Get the assets linked to this ticket.
    const ticketAssets = await this.prisma.ticketAsset.findMany({
      where: { ticketId: ticket.id },
      include: { asset: true }
    });

    if (ticketAssets.length === 0) return;

    // Get tenant settings to see if there is custom ITIL automation settings
    const tenant = await this.prisma.tenant.findUnique({
      where: { id: event.tenantId }
    });
    const settings = (tenant?.settings as any) || {};
    const itilRules = settings.itilAutomation || {
      enabled: true,
      timeWindowMinutes: 60,
      thresholdCount: 3,
    };

    if (!itilRules.enabled) return;

    // For each asset linked to the ticket, check for other recent tickets
    for (const ta of ticketAssets) {
      const assetId = ta.assetId;
      const asset = ta.asset;

      // Find tickets for the same asset within the timeWindowMinutes
      const timeWindow = new Date(Date.now() - itilRules.timeWindowMinutes * 60 * 1000);
      const recentTicketAssets = await this.prisma.ticketAsset.findMany({
        where: {
          assetId,
          ticket: {
            tenantId: event.tenantId,
            createdAt: { gte: timeWindow },
            status: { in: ['NEW', 'OPEN', 'IN_PROGRESS'] }
          }
        },
        include: { ticket: true }
      });

      const uniqueTickets = Array.from(new Map(recentTicketAssets.map(item => [item.ticketId, item.ticket])).values());

      if (uniqueTickets.length >= itilRules.thresholdCount) {
        // We hit the threshold! Check if there is already an active problem linked to this asset to avoid duplicate escalation
        const existingProblems = await this.prisma.problem.findMany({
          where: { tenantId: event.tenantId, status: { in: ['OPEN', 'ROOT_CAUSE_IDENTIFIED', 'KNOWN_ERROR'] } }
        });

        const alreadyHandled = existingProblems.some(p => {
          const affected = Array.isArray(p.affectedAssets) ? p.affectedAssets : [];
          return affected.some((a: any) => (typeof a === 'string' ? a === assetId : a.id === assetId));
        });

        if (alreadyHandled) {
          this.logger.debug(`Problem already active for asset ${asset.name} (${assetId})`);
          continue;
        }

        // Auto-promote: create a new Problem card
        const problemCount = await this.prisma.problem.count({ where: { tenantId: event.tenantId } });
        const problemNumber = `PRB-${String(problemCount + 1).padStart(5, '0')}`;
        
        const problemTitle = `Automated Incident Cluster: Multiple failures detected on ${asset.name}`;
        const problemDescription = `This problem record was automatically generated by the ITIL Automation Engine because ${uniqueTickets.length} active incidents were opened against asset "${asset.name}" (${asset.assetTag}) within a ${itilRules.timeWindowMinutes}-minute window.\n\nRelated Incidents:\n` +
          uniqueTickets.map(t => `- [${t.ticketNumber}]: ${t.subject} (Priority: ${t.priority})`).join('\n');

        const problem = await this.prisma.problem.create({
          data: {
            tenantId: event.tenantId,
            problemNumber,
            title: problemTitle,
            description: problemDescription,
            priority: 'HIGH',
            status: 'OPEN',
            category: 'Infrastructure',
            affectedAssets: [{ id: asset.id, name: asset.name, assetTag: asset.assetTag }] as any,
            relatedTickets: uniqueTickets.map(t => ({ id: t.id, ticketNumber: t.ticketNumber, title: t.subject })) as any,
            relatedChanges: [] as any,
          }
        });

        this.logger.log(`Auto-escalated ${uniqueTickets.length} incidents on ${asset.name} into Problem ${problemNumber}`);

        // Notify tenant administrators
        const admins = await this.prisma.user.findMany({
          where: {
            tenantId: event.tenantId,
            role: { name: { in: ['Tenant Admin', 'IT Admin'] } },
            status: 'ACTIVE',
          },
          select: { id: true },
        });

        for (const admin of admins) {
          await this.prisma.notification.create({
            data: {
              tenantId: event.tenantId,
              userId: admin.id,
              title: `🚨 Auto-Escalation: Problem Created`,
              message: `Multiple incidents on asset "${asset.name}" triggered the creation of Problem ${problemNumber}.`,
              type: 'ALERT',
              module: 'problems',
            },
          });
        }
      }
    }
  }
}
